// Wifi access setup
#define WLAN_SECURITY  WLAN_SEC_WPA2
#define WLAN_SSID      "YOUR WIFI SSID"
#define WLAN_PASS      "YOUR WIFI PASSWORD"

// WS2812 setup
#define NEOPIXEL_COUNT          16
#define NEOPIXEL_BRIGHTNESS     192
#define NEOPIXEL_MAX_BRIGHTNESS 255

